### ISSUE TITLE
Add a basic game interaction

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy-template#11]
Something that paints a metaphorical "YOUR GAME LOGIC HERE" sign.
I propose having a simple 2D sprite that moves on WASD like in https://github.com/NiklasEi/bevy_game_template

**Comment by MiniaczQ** [comment]
As mentioned in #3 
> We can simplify https://github.com/MiniaczQ/bevy-substate-based-ui down to a menu + credits

**Comment by janhohenheim** [comment]
This goes beyond what that template does, imo

**Comment by MiniaczQ** [comment]
We could add 2 separate update systems to help showcase the architecture better

As @benfrankel pointed out in #16, the UI code can be simplified down to setup, update, teardown, which can lead users to making a single update system for the entire game logic

**Comment by MiniaczQ** [comment]
From #32 we have a general direction of a 2D game, what can we make that needs ordering?
Maybe an input system + apply movement system?
