### ISSUE TITLE
Consult UI devs for proper user UI code management

### ISSUE THREAD

**Issue by MiniaczQ** [TheBevyFlock/bevy-template#30]
Mentioned in #16

**Comment by MiniaczQ** [comment]
Started a thread: https://discord.com/channels/691052431525675048/1258774289654612068

**Comment by MiniaczQ** [comment]
We conform to the general guidlines people are proposing, but it's hard to do this better without 3rd party crates.

I think we should document `ui/mod.rs` with various ui crates and templates

**Comment by janhohenheim** [comment]
The general vibe I got from this discussion and similar ones in #general is that offering a sickle-ui-like closure builder builder is the way to go (deferring to @brandon-reinhart here). I suggest doing a minimal reproduction of that style.

**Comment by MiniaczQ** [comment]
We could do a minimal support for closure container widgets (just `root` in out case), that's a bearable amount of boilerplate

I feel like adding more, especially widget builders, would be too much

**Comment by brandon-reinhart** [comment]
My preferences tend to be motivated by whatever lets me write less nested code and less NodeBundle and with_children boilerplate. Closure builders can help a bit. It's worth trying out different ideas, though!
