### ISSUE TITLE
Who is the audience for the template? 

### ISSUE THREAD

**Issue by Sapein** [TheBevyFlock/bevy-template#32]
This is something we probably need to consider a bit more, as I feel a bit more discussion on this would help direction a bit.

I'm asking because while this is a Jam Template, who are we targeting? To explain my thought process: Is our audience beginners, those who might barely know Bevy or more intermediate users, who have a bit of experience with bevy? 

If we're targeting beginners, then while we want to follow best practices, we might also want to limit or otherwise consider what we include so as to not make the template harder to use. I would also say that (at the very least) having recommendations for third-party crates wouldn't be the worst idea (even if we don't include them).

Also, for the template, are we looking at 2d/3d specific, or just being dimension-agnostic? Since this is a Jam template, I would prefer the latter one (dimension-agnostic), but that also means we have to be careful with how we organize things, although this might be better suited for a different discussion/issue entirely.

**Comment by janhohenheim** [comment]
Some quick thoughts:
- I think we should target people who have gone through the (very slim) Bevy book and know the basics, maybe even early intermediate users. I want the Jam to be accessible to new people
- Pointing out useful third-party crates sounds good. I'd keep it out of the code to not have rotten comments, but the readme seems like a good place. We can also point to other templates that make heavy use of third-party crates.
- Jam entries are overwhelmingly Wasm-based. In my experience, 3D on Wasm is just not quite there yet in Bevy. Yes, basic stuff like alien_cake_addict works, but go beyond that and your dev experience drastically tanks. It's possible to submit a Wasm 3D game to a Bevy jam, yes, but that is the realm of more advanced users or people with a lot of time on their hands. Let's keep it 2D for now.

**Comment by Sapein** [comment]
I'm fine with the first two, given that if we're targeting people who've only gone through the 'Bevy Book' and know just enough to get themselves into trouble, then we probably want to -- at the very least -- point them towards crates they would likely end up needing anyways (things like world inspector egui). 

If we're focusing on 2D then that does open up the crates we can suggest as well. My only concern with targeting only 2D, is that if 3D gets decent enough and we switch to include 3D or to be dimension-agnostic, then it could cause issues with people using this template after that change, which could pidgeon-hole this template to be 2D only. 

Obviously we could fix it with splitting the template into agnostic, 2d, and 3d (or just 2d and 3d) in the future, but it is something to be aware of.

**Comment by janhohenheim** [comment]
Since the "gameplay" layer of the template is extremely thin, changing it to 3D should be trivial imo. This could change when world-space UI becomes a thing, but that is still far off.

**Comment by janhohenheim** [comment]
I'll close this for now, but feel free to reopen if this is still a problem :)
