### ISSUE TITLE
Add VSCode settings

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy-template#33]
Should at least have the following:
```json
    "rust-analyzer.cargo.targetDir": true,
```

**Comment by benfrankel** [comment]
Is this the setting that makes rust-analyzer use a separate folder for its build cache? If so, doesn't that significantly increase disk usage?

**Comment by janhohenheim** [comment]
Yes. The increase is not *that* significant and it's needed on Windows for it to not sometimes decide to yeet your previous compilation.

**Comment by benfrankel** [comment]
It's unfortunate that JSON doesn't support comments... the tradeoff could be mentioned in the README, though.

**Comment by janhohenheim** [comment]
Agreed, a section about that on the readme seems wise

**Comment by benfrankel** [comment]
Huh, VS Code seems to allow `//` comments in `tasks.json` and `settings.json`, actually.
