### ISSUE TITLE
Provide tool to run release workflow locally

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy-template#49]
This would allow users to test their changes e.g. on itch.io without having to go through the whole commit + trigger and wait for CD process, improving iteration times. This is especially useful if you only want to do the release for one particular platform, or if you pay for CD.

My repo has a bash script for this, which is better than nothing but not portable.

**Comment by benfrankel** [comment]
I've also had issues locally cross-compiling from Linux to Mac, so if we can resolve that as well as part of this issue that would be cool.

**Comment by MiniaczQ** [comment]
I'm heavily against this, the compatibility with every user and maintenance aren't worth it.

**Comment by rparrett** [comment]
There was a small amount of discussion in the equivalent issue here:  https://github.com/bevyengine/bevy_github_ci_template/issues/8

**Comment by rparrett** [comment]
Just to elaborate on my reasoning for writing that other issue the way I did:

IMO, doing cross-platform native builds easily is half the reason for having this CI setup in the first place, and I don't really want to have to write / test / maintain the code that does that.

But the most problematic "cross-platform" situation is web, and being able to debug that without uploading to itch is pretty essential.

**Comment by benfrankel** [comment]
I can see reducing the scope to just web, at least to get this in before Bevy Jam 5.

**Comment by janhohenheim** [comment]
Very much agree with @rparrett and @MiniaczQ. We should have a way to easily run web builds locally, everything beyond that is out of scope for the moment.
I know many people use `trunk` for this, but I also know it has limitations in terms of what kind of build configuration it lets you pass along to `cargo`. Maybe they fixed that in the meantime, it's been a year or so since I looked into it.

**Comment by janhohenheim** [comment]
Update: do not use `trunk`. See @rparrett's writeup here: https://github.com/bevy-cheatbook/bevy-cheatbook/issues/253
