### ISSUE TITLE
Fix flickering at the start of the game

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy-template#6]
Migrated from https://github.com/bevyengine/bevy_github_ci_template/issues/61
Blocked by:
- [ ] https://github.com/bevyengine/bevy/issues/14135

**Comment by MiniaczQ** [comment]
In reference to #9, we should probably setup
```rs
CoreState {
  Loading,
  Running,
}
```
and rework the other state to a substate
```rs
#[derive(SubStates)]
#[source(CoreState = CoreState::Running)]
AppState {
  Menu,
  Game
}
```
