### ISSUE TITLE
Add `Serialize` and `Deserialize` to relevant types

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy-template#63]

**Comment by benfrankel** [comment]
This has been determined to be out of scope for now. The template itself currently doesn't need to make use of this, and it's not a particularly common use case for user code either (unlike e.g. `reflect(Resource)` for inspector, or `reflect(Component)` for blender).

**Comment by benfrankel** [comment]
:P

**Comment by benfrankel** [comment]
:P
