### ISSUE TITLE
Switch to a consistent `app.` style

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy-template#65]
Options:
1. Chain everything: `app.foo.bar.quux;`
2. Chain logical groups: `app.foo.bar; app.quux;`
3. Chain nothing: `app.foo; app.bar; app.quux;`

**Comment by MiniaczQ** [comment]
For me, in order: 3, 2, 1

**Comment by benfrankel** [comment]
My preference is for "chain nothing". Benefits:
1. Consistent alignment when every line begins with `app` instead of some beginning with 4 spaces.
2. Easy to move around and delete lines if the "logical groups" change, including copy/pasting lines from one plugin to another.
3. Cleaner git diffs.
4. No cognitive burden of deciding ahead of time whether you're about to add something to the same logical group or not, before you've even written it (1 and 3 share this benefit over 2).

These arguments can also be applied to avoiding `use foo::{bar, quux}` in favor of always splitting into `use foo::bar; use foo::quux`, but that's out of scope for this issue.

**Comment by janhohenheim** [comment]
I'm personally in camp 1 because I just really really like chaining functions in general. No big argument here, I just think it's neat to see every operation being done on the same type. The efficiency! The clarity! 

But if you two prefer style 3, I'll accept that I'm in the minority and use that style for the template.

**Comment by MiniaczQ** [comment]
I like chaining functions for builder patterns that use a variety of calls, but if we're doing 3 `add_plugins` and 7 `add_systems` and don't need to do anything after that (like a `build` that we then encapsulate in something, blah blah, typical web dev) I'd rather take the clarity
