### ISSUE TITLE
Setup a basic `State` enum for the game

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy-template#9]
*Migrated from https://github.com/bevyengine/bevy_github_ci_template/issues/64*

Same rationale as #4 
#6  is a good candidate for GameState::Boot.

**Comment by benfrankel** [comment]
As for bikeshedding the name. `GameState` and `AppState` are popularly used and familiar, but I would argue that in a game that has multiple state types for different things, they're kinda ambiguous names. What does "GameState" mean? Everything is a game state...

An alternative name would be something like `Screen` or `SequenceState`. I use `Screen` in my own template currently.

I'm totally fine with just going with `GameState` / `AppState` though, I don't think it'll cause any confusion for a jam-sized game.

**Comment by MiniaczQ** [comment]
As mentioned in #3 
> We can simplify https://github.com/MiniaczQ/bevy-substate-based-ui down to a menu + credits
