### ISSUE TITLE
Polish up a bit

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy-template#92]
- [x] Make the title screen a bit nicer (add an exit button, but not on web?)
- [ ] Make the credits screen a bit nicer
- [x] Make the playing screen a bit nicer (faster duck! wrap around edge of screen?)

**Comment by MiniaczQ** [comment]
1. Seems good, nothing fancy just a button that emits AppExit with 0
2. We can fill it with actual credits
3. I think this is done
4. Screen transitions seem like quite a bit of work, we don't even have a pattern for it, so we'd need to iterate, I'd make an issue and leave this for later

**Comment by MiniaczQ** [comment]
Screen transition moved to #104 with an implementation proposition

**Comment by janhohenheim** [comment]
I'll close this as the only remaining task is just #73
